name: CI - Analyse Statique

on:
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run static code analysis with semgrep
        uses: returntocorp/semgrep-action@v1.5.1
      
      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile
