name: CD - Build et Déploiement

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
      
      - name: Setup Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run unit tests
        run: npm test
      
      - name: Build Docker image
        run: |
          echo "Build started at: $(date -u)"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejsapp-cicd:latest .
          echo "Build completed at: $(date -u)"
      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Push Docker image
        run: |
          echo "Push started at: $(date -u)"
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejsapp-cicd:latest
          echo "Push completed at: $(date -u)"
      
      - name: Get Docker image checksum
        run: |
          IMAGE_ID=$(docker images ${{ secrets.DOCKER_USERNAME }}/nodejsapp-cicd:latest -q)
          CHECKSUM=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_ID)
          echo "Docker image checksum: $CHECKSUM"

      - name: Run static code analysis with semgrep
        uses: returntocorp/semgrep-action@v1.5.1  
      
      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile
      
      - name: Setup Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
      
      - name: Scan for vulnerabilities
        run: trivy image ${{ secrets.DOCKER_USERNAME }}/nodejsapp-cicd:latest
